config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :customers, :except => [:destroy] 
  #nested routing where reviews is nested under products
  resources :products do
  	resources :reviews
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	#has_and_belongs_to_many :products
	has_many :reviews
	has_many :products, through: :reviews

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews 
	has_many :customers, through: :reviews

	validates :name, presence: true, length: {in: 4..50}
	validates :description, presence: true
	validates :price_in_cents, numericality: {only_integer: true, :greater_than_or_equal_to => 0}

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :customer
	belongs_to :product

	validates :review, presence: true, length: {in: 4..50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@title = "All Products"
		@products = Product.all
	end

	def create
		@title = 'Create New Product'

		@product = Product.new
		@product.name = params[:product][:name]
		@product.description = params[:product][:description]
		@product.price_in_cents = params[:product][:price_in_cents]

		if @product.save
			#redirect_to products_path
			redirect_to product_path(@product)

		else
			render :new
		end
	end

	def new
		@title = 'Create new Product'
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
		@product_reviews = @product.reviews
		@title = @product.name
		@review = Review.new
		#review instance is being made here

	end

	def edit
		id = params[:id]
		@product = Product.find(id)
	end
	
	def update
		@product = Product.find(params[:id])

		@product.name = params[:product][:name]
		@product.description = params[:product][:description]
		@product.price_in_cents = params[:product][:price_in_cents]

		if @product.save
			redirect_to product_path
		else
			render :index
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		#puts "Creating new review"
		@review = Review.new

		@review.review = params[:review][:review]
		@review.product_id = params[:product_id]
		 #check server log to make this clear
		 @review.customer_id = 1
		if @review.save
			redirect_to product_path(id: params[:product_id])
		else
			flash[:warning] = @review.errors.full_messages
		 	redirect_to product_path(id: params[:product_id])
		end
	end


	def edit
		id = params[:id]
		@review = Review.find(id)
		@product = @review.product 
	end 
	
	def update
		id = params[:product_id]
		@review = Review.find(params[:id])
		@product = Product.find(params[:product_id])

		@review.review = params[:review][:review]
		
		if @review.save
			redirect_to product_path(id: id)
		else
			render :edit
		end
	end

	def destroy
		id = params[:product_id]
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to product_path(id: id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<h1>Rainforest</h1>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_product_form.html.erb
<% if a_product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(a_product.errors.count, "error") %> prohibited this product from being saved:</h2>
	<ul>
		<% a_product.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<%= form_for a_product do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>

	<p>
		<%= f.label :price_in_cents %><br>
		<%= f.number_field :price_in_cents %>
	</p>


	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>

app/views/products/_single_product.html.erb
<div class="product">
	<h2>name: <%= link_to a_product.name, product_path(a_product) %></h2>
	<h3>description: <%= a_product.description %></h3>
	<h4>date added: <%= a_product.created_at %></h4>
	<br>
	<strong>
		price in cents: $<%= a_product.price_in_cents %>
	</strong>
</div>

app/views/products/edit.html.erb
<h2> Edit <%= link_to @product.name, product_path(@product) %>
	
</h2>
<%= render 'product_form', a_product: @product %> 

app/views/products/index.html.erb
<title><%= @title %></title>
<h2> Products </h2>
<%= link_to("Add New Product", "products/new") %>

<% @products.each do |product| %> 
	<%= render 'single_product', a_product: product %>
<% end %>

app/views/products/new.html.erb
<h2>Create New product</h2>
<%= link_to 'Back to Products', products_path %> 
<%= render 'product_form', a_product: @product %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<div>
	<%= link_to 'Back to Products', products_path(@product) %>
</div>
<%= render 'single_product', a_product: @product %>


<div>
	<%= link_to 'Edit', edit_product_path %>
	<%= link_to 'Delete product', product_path(@product), method: :delete, data: {confirm: "are you sure you want to delete this '#{@product.name}'?"} %>
</div>

<%= render partial: '/reviews/review_form', locals: {a_review: @review, id: @product.id } %>

<h2> Reviews for <%= @product.name %></h2>
	<ul>
<% @product_reviews.each do |a_review| %>
		<li>
			<%= a_review.review %>
			<%= a_review.customer.name %>
			<%= a_review.created_at %>
			<%= link_to 'Edit', edit_product_review_path(@product, a_review) %>
			<%= link_to 'Delete', product_review_path(@product, a_review), method: :delete, data: {confirm: "are you sure you want to delete this comment by '#{a_review.customer.name}'?"} %> 
		</li>
<% end %>
	</ul>

app/views/reviews/_review_form.html.erb
<%= form_for a_review, url: product_reviews_path(id) do |f| %> 
	<p>
		<%= f.label :review %><br>
		<%= f.text_field :review %> 
	</p>
	
	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>

<% if flash[:warning]%>
	<% flash[:warning].each do |error| %>
		<%= error %><br/>
	<%end%>
<%end%>

app/views/reviews/edit.html.erb
<br>
<% if @review.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@review.errors.count, "error") %> prohibited this product from being saved:</h2>
	<ul>
		<% @review.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
		<% end %>
<br>
<%= form_for @review, url: product_review_path(@product.id, @review.id) do |f| %> 
	<p>
		<%= f.label :review %><br>
		<%= f.text_field :review %> 
	</p>
	
	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>